### ISSUE TITLE
Guests in clan chat are not counted

### ISSUE THREAD

**Issue by ziggyman77** [JoRouss/runelite-ClanEventAttendance#12]
Could we get an option to count guests? Our trials in clan are unranked guests. This would make it a ton easier. Thanks!

**Comment by JoRouss** [comment]
Thanks for your suggestion, I can look into this for sure. It's a good idea.

Give me a few days :)

**Comment by JoRouss** [comment]
I looked into this and there is currently no way to pick up clan guests in the Runelite API. We'll have to wait till this is possible.

I'll leave the issue open and keep an eye on it.

**Comment by JoRouss** [comment]
I forgot to mention, until there's progress on this, you can use a friends chat to track guests.
